[workspace.package]
name = "money-view"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["server"]
default-members = ["server"]
resolver="2"

[workspace.dependencies]
tonic-build = "0.12.1"
tonic = "0.12.1"
tonic-web = "0.12.1"
tonic-reflection = "0.12.1"
tonic-types = "0.12.1"
